version: '3'
services:
  app:
    image: ${APP_IMAGE}
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    environment:
      SETTINGS_PATH: /workspace/settings.yml
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: >
      gunicorn --workers 2 --threads 2 --reload --bind :${APP_PORT} celineyeh.web.server

  dev:
    image: ${APP_IMAGE_DEV}
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
    environment:
      SETTINGS_PATH: /workspace/settings.yml
    command: bash
